server:
  port: 9999

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: trading-service
          uri: lb://trading
          predicates:
            - Path=/api/trade/**
        - id: portfolio-service
          uri: lb://portfolio
          predicates:
            - Path=/api/portfolio/**
        - id: registration-service
          uri: lb://registration
          predicates:
            - Path=/api/auth/**
        - id: exchange-service
          uri: lb://exchange
          predicates:
            - Path=/api/exchange/**

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/
